### PR TITLE
Fix: [BUG-226] JSONPath wilcard selector not supported

### PR DESCRIPTION
**Pull request by GaneshSelvarasu**
Fixes [226](https://github.com/stepci/stepci/issues/226)

### CODE REVIEW

**Comment by GaneshSelvarasu** [comment]
The  "in" and "nin" matchers may be impacted by the proposed solution. Consider the check, 

```
check:
  jsonpath:
    $.items[*].name:
      - in: "Car"
```

The check would work as intended if we input the below JSON, 
```
{
  "items": [
    {
      "name": "Card"
    },
    {
      "name": "Car"
    }
  ]
}
```

However, the above check would still pass if we input the below one which is inappropriate.
```
{
  "items": [
    {
      "name": "Card"
    }
  ]
}
```

The reason is that the items have a single element and in this case, the first element (a string value) is sent to checkResult().

Therefore, for these two matchers, we would want to convert the "given" data to an array, if it is not, so that the second case would fail.

Please share your thoughts.

**Comment by mishushakov** [comment]
Not gonna work. Have you looked at providing `wrap: false` instead? This should return single hit unless it returns array.

Ref: https://www.npmjs.com/package/jsonpath-plus

**Comment by GaneshSelvarasu** [comment]
I agree. I failed to learn about the `wrap` option. I will update this. 

Just curious, will adding `wrap` in workflow config help?

**Comment by mishushakov** [comment]
Have you tested it yet? Does it work as expected?

**Comment by GaneshSelvarasu** [comment]
Yes, and it works as expected.

**Comment by mishushakov** [comment]
Thank you very much!

**Pull request merged**
