### PR TITLE
parseTemplate

### PR DESCRIPTION
**Pull request by fmalk**
@mishushakov there's the first PR - https://github.com/stepci/runner/issues/33
What I did here was:

- Remove mustache as dependency
  - By using `flat` we can use `replaceAll()` only where needed
  - Only strict, known properties will be parsed
- Type declaration in `types.ts`

I added my test case for you to help me test it. See if you like this direction but I'll improve this PR with any suggestions you might have.
Sorry for the time this PR took, I'm still traveling and I had a few issues setting this project up for testing (I created another test.ts to run files from yml, but I struggled a bit in VS Code). Also, your recent commits conflicted in a few places, I had to redo my commits 😄

### CODE REVIEW

**Comment by mishushakov** [comment]
Hello, @fmalk
No worries, we are not in a rush! The most important thing for me and Sebastian is that our contributors enjoy working on the project as much as we do 😄 

Right now, I'm thinking of turning the `parseTemplate` thingy into a library, which can be used for templating arbitrary JS objects

Other projects, which also use YAML or JSON for configuration could benefit from greatly from it
What do you think?

**Comment by fmalk** [comment]
Oh right, at first I looked in the codebase for some cloning function you might have had already, didn't find one but then I forgot to do one on my own. I'll update the PR with something like that.
If you want to do that parse as a lib, you should try to really look if that's something we wouldn't find elsewhere first. Because with my code as it is, I didn't even thought about performance (or even deep copies as you pointed out).

**Comment by mishushakov** [comment]
I don't think you have to put any more effort into this PR 😁

Yeah, I have tried searching NPM to see if something like this exists and found some packages, but they're not too interesting:

https://www.npmjs.com/package/obj-template
https://www.npmjs.com/package/template-object
https://www.npmjs.com/package/json-templater
https://www.npmjs.com/package/traverse-template

Personally, I'm a big fan of [Vue templates](https://vuejs.org/guide/essentials/template-syntax.html#using-javascript-expressions), which uses JavaScript and [LiquidJS](https://liquidjs.com/tutorials/render-tag-content.html), based on Shopify's Liquid template language

We'll have to try both to decide which one is a better fit for our use-case

**Comment by fmalk** [comment]
Well, I think there's only two points regarding this PR:

- Rewrite how to do a copy of the step object first
- If you want me to leave the `types.ts` as it is, or if I should move it back so it won't interfere with https://github.com/stepci/runner/issues/45 later

**Comment by mishushakov** [comment]
I'll close this PR for now and will setup a repo for our template parser. We can continue the discussion here and once we have some working code, we can open a PR here again to make use of the library!

**Comment by mishushakov** [comment]
I have setup a repository with some boilerplate code here: https://github.com/stepci/liquid-lite

You can read more about what we'll be building in this doc: https://github.com/stepci/liquid-lite/issues/1
Feel free to ask any questions!

Thanks

**Pull request closed without merging**
